### ISSUE TITLE
Plan for a v1

### ISSUE THREAD

**Issue by mvdan** [go-quicktest/qt#7]
I assume that you've likely tagged this newer and generic version of https://github.com/frankban/quicktest as a v0 so that you can polish the API some more before freezing it, and I also understand why - generics are rather new and mistakes will be made.

I wonder, is therre a rough plan or timeline for a v1 tag? Once Go 1.19 is out in about four months, most projects will only support Go 1.18+ in master at that point, so starting to use a generic quicktest will become more reasonable. It would be nice to be able to transition from the older library without having to worry about v0 breakages :)

**Comment by gilcrest** [comment]
I'm wondering the same thing - if you feel it's ready enough for basic alpha/beta usage, I'm happy to switch my personal projects to this and try to help build out the readme (see #10 ), but don't want to jump in too early if it's not helpful.

**Comment by frankban** [comment]
I think this is getting ready for a stable release.
By looking at the API, I am happy with the new Checker interface, and therefore how checkers are implemented and used.

I am not sure about the following names, suggestions are welcome:
- https://pkg.go.dev/github.com/go-quicktest/qt#F2
- MapAny, MapAll, SliceAny, SliceAll (they were just Any and All in quicktest): at least for me it seems that they suggest that something is mapped or sliced, rather than something needs to be true for one or all elements of a map or a slice. But I didn't find anything better: AnyInMap/AllInMap is not great and also not consistent with MapContains.

**Comment by marco-m** [comment]
`F2` does a sort of [partial application](https://en.wikipedia.org/wiki/Partial_application), so maybe `PartialChecker` or similar?

**Comment by frankban** [comment]
We have released a v1, closing this.
